/**
 * Utility to parse the Excel data into the format expected by the import edge function
 * This converts the parsed document data into a structured format
 */

export const dormDataFromExcel = [
  {
    "Dorm": "Dorm B",
    "Monthly Price (prices are per student, not per room)": "SS: $505, SD: $380, HSS: $550, HSD: $419, SA: $790, LA: $835",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Standard (Single/Double), High Standard (Single/Double), Small Apartment (for 2), Large Apartment (for 2)",
    "Capacity": "SS, HSS: 1. SD, HSD: 2. SA, LA: 2",
    "Phone Number": "09 547 262, ext. 2501",
    "Services & Amenities": "24/7 electricity included, Heating & AC, Hot water 24/7, TV, Desks, fridge, Safety Boxes, kitchenette, High-Speed WiFi, cleaning, study areas & lounges, maintenance & laundry services",
    "Walking distance": "<1 min to LAU Main Gate"
  },
  {
    "Dorm": "UniView",
    "Monthly Price (prices are per student, not per room)": "S: $375, D: $550, D: $750",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double, Triple",
    "Capacity": "S: 1. D:2. T:3",
    "Phone Number": "81 601 111",
    "Services & Amenities": "24/7 electricity included, AC, TV, fridge, WiFi, cleaning 2 days per week, maintenance & laundry services, access to gym and underground parking",
    "Walking distance": "<1 min to LAU Main Gate"
  },
  {
    "Dorm": "Cronus",
    "Monthly Price (prices are per student, not per room)": "S: $550, D: $900, D: $1000",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double (apartment-like: 1 bedroom, salon, kitchenette..)",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "76 304 040/09 543 217/09 543 218/09 543 219",
    "Services & Amenities": "24/7 electricity included, AC, Balcony, TV, fridge, WiFi, cleaning, maintenance & laundry services, access to gym and underground parking",
    "Walking distance": "Walking: 5 mins to LAU Main Gate. Shuttle: 1 min"
  },
  {
    "Dorm": "Valley",
    "Monthly Price (prices are per student, not per room)": "S: $350",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "70 557 253/76 337 430",
    "Services & Amenities": "50 KW free each month, TV, fridge, kitchenette, WiFi, cleaning, study areas & lounges, maintenance & laundry services, access to gym",
    "Walking distance": "Walking: 5 mins to LAU Main Gate. Shuttle: 1 min"
  },
  {
    "Dorm": "Bahous 1",
    "Monthly Price (prices are per student, not per room)": "SS: $340, SD: $400, ST: $450, MS: $390, MD: $450, MT: $510, LS: $440, LD: $540, LT: $630, LQ: $760",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Small (Single/Double/Triple), Medium (Single/Double/Triple), Large (Single/Double/Triple/Quad)",
    "Capacity": "S: 1. D:2. T:3",
    "Phone Number": "81 592 000/09 542 852",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, study areas & lounges, maintenance & laundry services",
    "Walking distance": "Walking: <1min to LAU Main Gate"
  },
  {
    "Dorm": "Majesty Villa (Mary Dorm)",
    "Monthly Price (prices are per student, not per room)": "SS: $475, HSS: $500, SD: $600, HSD: $650",
    "Deposit": "$100",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Standard (Single/Double), High Standard (Single/Double)",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "03 032 953/09 944 733",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning 3 days per week, private parking, maintenance & laundry services",
    "Walking distance": "Walking: <1min to LAU Main Gate"
  },
  {
    "Dorm": "H-Dorms",
    "Monthly Price (prices are per student, not per room)": "S: $350",
    "Deposit": "$150",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "81 625 299",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: <1min to LAU Main Gate"
  },
  {
    "Dorm": "Elite Residence",
    "Monthly Price (prices are per student, not per room)": "S: $300, D: $500",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Next to Sweet Home",
    "Room Type": "Single, Double, Junior Suite, Royal Suite",
    "Capacity": "S: 1. D: 2. JS: 1. RS: 1",
    "Phone Number": "76 501 313",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: 2 mins to LAU Main Gate"
  },
  {
    "Dorm": "Lux",
    "Monthly Price (prices are per student, not per room)": "S: $280, S: $300, D: $450, D: $500",
    "Deposit": "$250",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "71 999 403",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: 7 mins to Main Gate. Shuttle: 1 min"
  },
  {
    "Dorm": "Sweet Dorms",
    "Monthly Price (prices are per student, not per room)": "S: $300, D: $450",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "76 465 201/76 572 688",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: 2 mins to LAU Main Gate"
  },
  {
    "Dorm": "The Loft",
    "Monthly Price (prices are per student, not per room)": "S: $350, S: $375, S: $450, D: $550, D: $650, D: $750",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "71 465 641",
    "Services & Amenities": "100 KW free every month, TV, fridge, kitchenette, WiFi, cleaning once per week, gym, maintenance & laundry services",
    "Walking distance": "Shuttle: 2 mins"
  },
  {
    "Dorm": "Patrick",
    "Monthly Price (prices are per student, not per room)": "$200",
    "Deposit": "$100",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single",
    "Capacity": "S: 1.",
    "Phone Number": "70 979 232/81 238 113",
    "Services & Amenities": "TV, fridge, kitchenette, cleaning, maintenance & laundry services",
    "Walking distance": "15 mins walk to LAU Main Gate"
  },
  {
    "Dorm": "Belle Vue",
    "Monthly Price (prices are per student, not per room)": "$250",
    "Deposit": "$100",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "76 002 483",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "15 mins walk to LAU Main Gate"
  },
  {
    "Dorm": "Ever home",
    "Monthly Price (prices are per student, not per room)": "S: $375, S: $400",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "70 943 766",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: 15 mins to LAU Main Gate. Shuttle: 2 mins"
  },
  {
    "Dorm": "Salemeh",
    "Monthly Price (prices are per student, not per room)": "S: $200",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "03 785 673",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "15 mins walk to LAU Main Gate"
  },
  {
    "Dorm": "Rest Residence",
    "Monthly Price (prices are per student, not per room)": "$300",
    "Deposit": "$100",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "76 625 822",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "20 mins walk to LAU Main Gate"
  },
  {
    "Dorm": "Oasis",
    "Monthly Price (prices are per student, not per room)": "$230",
    "Deposit": "$200",
    "City": "Blat",
    "Shuttle": "No",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "71 653 112",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning once per week, maintenance & laundry services",
    "Walking distance": "20 mins walk to LAU Main Gate"
  },
  {
    "Dorm": "Bahous 2",
    "Monthly Price (prices are per student, not per room)": "S: $250",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "81 599 778",
    "Services & Amenities": "TV, fridge, kitchenette, WiFi, cleaning, maintenance & laundry services",
    "Walking distance": "Walking: 10 mins to Main Gate. Shuttle: 1 min"
  },
  {
    "Dorm": "Leona",
    "Monthly Price (prices are per student, not per room)": "$700",
    "Deposit": "Same as monthly rent",
    "City": "Blat",
    "Shuttle": "Yes",
    "Address": "Byblos, Jbeil - Near Lebanese American University (LAU), Byblos, Liban",
    "Room Type": "Single, Double",
    "Capacity": "S: 1. D:2.",
    "Phone Number": "71 555 200",
    "Services & Amenities": "Gym, parking, TV, fridge, kitchenette, WiFi, daily cleaning, maintenance & laundry services",
    "Walking distance": "Shuttle: 3 mins"
  }
];
